DROP TABLE CATEGORIA CASCADE CONSTRAINTS; -- Esta Funcao ira deletar a relacao com as outras tabelas, depois deleta a tabela

CREATE TABLE CATEGORIA(
    COD_CATEGORIA INT CONSTRAINT PK_CATEGORIA_COD_CATEGORIA PRIMARY KEY,
    CATEGORIA VARCHAR(255)
    CONSTRAINT UK_CATEGORIA_CATEGORIA UNIQUE
    CHECK (CATEGORIA IN ('DOCE', 'BEBIDA', 'CONGELADO'))
);


CREATE TABLE MATERIA_PRIMA (
    COD_MATERIA_PRIMA INT CONSTRAINT PK_MP_COD_MAT_PRIMA PRIMARY KEY,
    MATERIA_PRIMA VARCHAR(255) CONSTRAINT UK_MP_MATERIA_PRIMA UNIQUE
);


CREATE TABLE PRODUTO (
    COD_PRODUTO INT CONSTRAINT PK_PRD_COD_PRODUTO PRIMARY KEY,
    PRODUTO VARCHAR(255) CONSTRAINT UK_PRD_PRODUTO UNIQUE,
    COD_CATEGORIA INT CONSTRAINT UK_PRD_COD_CATEGORIA UNIQUE,
    CONSTRAINT FK_PRD_CAT_COD_CATEGORIA
    FOREIGN KEY (COD_CATEGORIA)
    REFERENCES CATEGORIA (COD_CATEGORIA)
);

CREATE TABLE ITEM_PRODUTO (
    COD_PRODUTO INT,
    COD_MATERIA_PRIMA INT,
    QUANTIDADE INT NOT NULL UNIQUE,
    CONSTRAINT PK_IT_CP_CMP PRIMARY KEY (COD_PRODUTO, COD_MATERIA_PRIMA),
    CONSTRAINT FK_IT_COD_PRODUTO FOREIGN KEY (COD_PRODUTO)
    REFERENCES PRODUTO (COD_PRODUTO),
    CONSTRAINT FK_IT_COD_MAT_PRIMA FOREIGN KEY (COD_MATERIA_PRIMA)
    REFERENCES MATERIA_PRIMA (COD_MATERIA_PRIMA)
);


--------------------------------------------------------------------------
SELECT TABLE_NAME,
CONSTRAINT_TYPE,
CONSTRAINT_NAME,
SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('CATEGORIA','PRODUTO','MATERIA_PRIMA','ITEM_PRODUTO')
ORDER BY 1,2,3;

