-- Ajuste para o primeiro exercício

ALTER TABLE DB_FUNCIONARIO
ADD CD_DEPTO NUMBER(3);

ALTER TABLE DB_FUNCIONARIO
ADD CONSTRAINT FK_DB_FUNC_DEPTO
FOREIGN KEY (CD_DEPTO)
REFERENCES DB_DEPTO;

UPDATE DB_FUNCIONARIO
SET CD_DEPTO = 1
WHERE NM_FUNCIONARIO LIKE 'A%'
OR NM_FUNCIONARIO LIKE 'C%'
OR NM_FUNCIONARIO LIKE 'D%';

UPDATE DB_FUNCIONARIO
SET CD_DEPTO = 5
WHERE NM_FUNCIONARIO LIKE 'J%'
OR NM_FUNCIONARIO LIKE 'H%'
OR NM_FUNCIONARIO LIKE 'K%';

UPDATE DB_FUNCIONARIO
SET CD_DEPTO =13
WHERE NM_FUNCIONARIO LIKE 'E%'
OR NM_FUNCIONARIO LIKE 'I%'
OR NM_FUNCIONARIO LIKE 'M%';

UPDATE DB_FUNCIONARIO
SET CD_DEPTO = 14
WHERE NM_FUNCIONARIO LIKE 'J%'
OR NM_FUNCIONARIO LIKE 'H%'
OR NM_FUNCIONARIO LIKE 'K%';

UPDATE DB_FUNCIONARIO
SET CD_DEPTO = 20
WHERE NM_FUNCIONARIO LIKE 'B%'
OR NM_FUNCIONARIO LIKE 'O%'
OR NM_FUNCIONARIO LIKE 'G%';

UPDATE DB_FUNCIONARIO
SET CD_DEPTO = 47
WHERE NM_FUNCIONARIO LIKE 'T%'
OR NM_FUNCIONARIO LIKE 'N%';

UPDATE DB_FUNCIONARIO
SET CD_DEPTO = 48
WHERE NM_FUNCIONARIO LIKE 'L%'
OR NM_FUNCIONARIO LIKE 'P%';

UPDATE DB_FUNCIONARIO
SET CD_DEPTO = 49
WHERE NM_FUNCIONARIO LIKE 'R%'
OR NM_FUNCIONARIO LIKE 'S%';

COMMIT;
