-------------------------------------------------------
-- Exemplos: Banco de Dados - Programação Aula 5
-------------------------------------------------------
-- REMOVE AS TABELAS
DROP TABLE PRODUTO CASCADE CONSTRAINTS PURGE;
DROP TABLE CIENTISTA CASCADE CONSTRAINTS PURGE;

-- CRIAÇÃO DE TABELAS E INSERÇÃO DE LINHAS
CREATE TABLE PRODUTO
(CODIGO    INTEGER     PRIMARY KEY,
 DESCRICAO VARCHAR(50) NOT NULL,
 VALOR     NUMBER(6,2) NOT NULL);

INSERT INTO PRODUTO
VALUES (100,'CAMISETA',80.00);
 
INSERT INTO PRODUTO
VALUES (101,'POLO',120.00);

INSERT INTO PRODUTO
VALUES (102,'CAMISA',150.00);

INSERT INTO PRODUTO
VALUES (103,'CAL�A',100.00);

INSERT INTO PRODUTO
VALUES (104,'SHORTS',70.00);

COMMIT;

CREATE TABLE CIENTISTA
(CODIGO  INT         PRIMARY KEY,
 NOME    VARCHAR(50) NOT NULL,
 DT_NASC DATE,
 SEXO    CHAR(1) );

INSERT INTO CIENTISTA 
VALUES (1010,'STEPHEN HAWKING','08/01/1942','M');

INSERT INTO CIENTISTA 
VALUES (1011,'ALBERT EINSTEIN','14/03/1879','M');

INSERT INTO CIENTISTA 
VALUES (1012,'ISAAC NEWTON','04/01/1643','M');

INSERT INTO CIENTISTA 
VALUES (1013,'GALILEU GALILEI','15/02/1564','M');

INSERT INTO CIENTISTA 
VALUES (1014,'NICOLAU COPERNICO','19/02/1473','M');
COMMIT;

-------------------------------------------------------
-- Exemplos
-------------------------------------------------------
-- O SELECT (RETORNANDO TODAS AS COLUNAS E LINHAS)- (PROJEÇÃO)
SELECT *
FROM PRODUTO;

-- O SELECT (RETORNANDO TODAS AS LINHAS E DETERMINADAS COLUNAS)- (PROJEÇÃO)
SELECT DESCRICAO, VALOR
FROM PRODUTO;

-- O SELECT (UTILIZANDO OPERADORES ARITMÉTICOS)
SELECT DESCRICAO, VALOR, VALOR * 1.13 AS VAL_CALC
FROM PRODUTO;

SELECT DESCRICAO,VALOR, (VALOR + 10) * 1.05 
FROM PRODUTO;

-- O SELECT (UTILIZANDO APELIDOS)
SELECT DESCRICAO, VALOR * 1.13 AS VLR_CALCULADO
FROM PRODUTO;

SELECT DESCRICAO, (VALOR + 10) * 1.05 AS VLR_CALCULADO 
FROM PRODUTO;

-- O COMANDO SELECT ORDENANDO RESULTADOS
SELECT * 
FROM PRODUTO 
ORDER BY VALOR DESC;

SELECT * 
FROM PRODUTO 
ORDER BY VALOR ASC;


-- O COMANDO SELECT UTILIZANDO WHERE
SELECT DESCRICAO, VALOR
FROM PRODUTO
WHERE VALOR > 100;

-- O SELECT (UTILIZANDO FILTRO) - (SELEÇÃO)-(OPERADORES RELACIONAIS/COMPARAÇÃO)
SELECT *
FROM PRODUTO
WHERE VALOR > 100;

-- OPERADOR DE COMPARAÇÃO BETWEEN

SELECT DESCRICAO, VALOR
FROM PRODUTO
WHERE VALOR BETWEEN 80 AND 120;

-- OPERADOR DE COMPARAÇÃO LIKE
SELECT NOME, DT_NASC
FROM CIENTISTA
WHERE NOME LIKE 'S%';

SELECT NOME, DT_NASC
FROM CIENTISTA
WHERE NOME LIKE '%AA%';

SELECT NOME, DT_NASC
FROM CIENTISTA
WHERE NOME LIKE '%O';

-- OPERADOR DE COMPARAÇÃO LIKE (UNDERLINE)
SELECT NOME, DT_NASC
FROM CIENTISTA
WHERE NOME LIKE '_T%';

SELECT NOME, DT_NASC
FROM CIENTISTA
WHERE NOME LIKE '__A%';

SELECT NOME, DT_NASC
FROM CIENTISTA
WHERE NOME LIKE 'N_C%';

-- OPERADORES LÓGICOS
SELECT DESCRICAO, VALOR
FROM PRODUTO
WHERE VALOR > 100
AND DESCRICAO LIKE 'CA%';

----------------------------------------------------------
SELECT EMPLOYEE_ID, LAST_NAME, SALARY, COMMISSION_PCT FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, COMMISSION_PCT, JOB_ID FROM EMPLOYEES
WHERE (LAST_NAME LIKE 'A%'
OR SALARY > 5000)
AND JOB_ID = 'IT_PROG';


DROP TABLE EMPOLYEES_BKP;
CREATE TABLE EMPOLYEES_BKP AS SELECT * FROM EMPLOYEES WHERE 1 = 2;  -- o WHERE e feito dessa forma para criar a estrutura da tabela porem vazia

SELECT * FROM EMPOLYEES_BKP;




