DROP TABLE ALUNOS;
DROP TABLE FILIACOES;

-- CRIA TABELA
    CREATE TABLE ALUNOS
    (RM       NUMBER(5),
    NOME      VARCHAR(25) CONSTRAINT ALUNOS_NOME_NN      NOT NULL,
    SOBRENOME VARCHAR(25) CONSTRAINT ALUNOS_SOBRENOME_NN NOT NULL);

--************************************ COMANDO ALTER ************************************--
-- ADICIONA UMA COLUNA
    ALTER TABLE ALUNOS
    ADD DT_NASCIMENTO DATE;

-- ADICIONA MAIS DE UMA COLUNA
    ALTER TABLE ALUNOS
    ADD (GENERO       CHAR(1) CONSTRAINT ALUNOS_GENERO_NN NOT NULL,
         COD_FILIACAO NUMBER(5));

-- REMOVE UMA COLUNA    
    ALTER TABLE ALUNOS
    DROP COLUMN DT_NASCIMENTO;

-- ADICIONA CONSTRAINT PK NOMEADA
    ALTER TABLE ALUNOS
    ADD CONSTRAINT ALUNOS_PK PRIMARY KEY (RM); 
 
-- CRIA TABELA COM PK NO NÍVEL DA COLUNA
    CREATE TABLE FILIACOES
    (COD_FILIACAO NUMBER(5) CONSTRAINT FILIACOES_PK PRIMARY KEY,
     NOME_MAE     VARCHAR(100),
     NOME_PAI     VARCHAR(100));

-- ADICIONA UMA FK (LEMBRE-SE DE QUE A TABELA (FORTE/PAI) DE EXISTIR POIS ELA SERÁ REFERENCIADA)
    ALTER TABLE ALUNOS
    ADD
    CONSTRAINT ALUNOS_FILIACOES_FK
    FOREIGN KEY (COD_FILIACAO)
    REFERENCES FILIACOES;
--  REFERENCES FILIACOES(COD_FILIACAO); --NOTE QUE NÃO É NECESSÁRIO INFORMAR O NO DA PK

-- REMOVE UMA CONSTRAINT
    ALTER TABLE ALUNOS
    DROP CONSTRAINT ALUNOS_NOME_NN;

-- REMOVE MAIS DE UMA CONSTRAINT
    ALTER TABLE ALUNOS
    DROP CONSTRAINT ALUNOS_GENERO_NN
    DROP CONSTRAINT ALUNOS_SOBRENOME_NN;

-- DESABILITA UMA CONSTRAINT
    ALTER TABLE ALUNOS
    DISABLE CONSTRAINT ALUNOS_FILIACOES_FK;

-- HABILITA UMA CONSTRAINT
    ALTER TABLE ALUNOS
    ENABLE CONSTRAINT ALUNOS_FILIACOES_FK;

--************************************ COMANDO ALTER COM MODIFY ************************************--
-- ALTERAR (MODIFICAR) O TAMANHO DE UMA COLUNA
--EXIBE A ESTRUTURA DA TABELA
    DESCRIBE ALUNOS; 

    ALTER TABLE ALUNOS
    MODIFY NOME VARCHAR(50);

--O DESCRIBE PODE SER ABREVIADO POIS NÃO É UM COMANDO SQL
    DESC ALUNOS; 

-- ALTERAR (MODIFICAR) O TAMANHO DE MAIS DE UMA COLUNA
    ALTER TABLE ALUNOS
    MODIFY NOME VARCHAR(100)
    MODIFY SOBRENOME VARCHAR(100);
    
    DESC ALUNOS; 

--************************************ COMANDO DROP ************************************--
-- DROPANDO TABELA
    DROP TABLE FILIACOES;
    DROP TABLE FILIACOES CASCADE CONSTRAINTS;
-----------------------------------------------------------------------------
-- ESPECIAL (RETIRANDO DA RECYCLEBIN) * SÓ NO ORACLE DATABASE - 
-- CUDADO: SOMENTE TABELAS VÃO PARA A LIXEIRA OUTROS OBJETOS NÃO!
-- COMANDO FLASHBACK TABLE
    FLASHBACK TABLE FILIACOES TO BEFORE DROP;

-- ATENÇÃO: SE ELA SE RELACIONAVA COM OUTRA TABELA A FK DEVE SER RECRIADA

   -- TIRANDO A PROVA PARA COMPROVAR QUE NÃO TEMOS MAIS A FOREIGN KEY
        SELECT
            CONSTRAINT_NAME,
            CONSTRAINT_TYPE
        FROM USER_CONSTRAINTS 
        WHERE TABLE_NAME = 'ALUNOS'; 
        
     -- ADICIONANDO A FOREIGN KE   
        ALTER TABLE ALUNOS
        ADD
        CONSTRAINT ALUNOS_FILIACOES_FK
        FOREIGN KEY (COD_FILIACAO)
        REFERENCES FILIACOES;

-- DROPA DEFINITIVAMENTE A TABELA
    DROP TABLE FILIACOES PURGE;
    DROP TABLE FILIACOES CASCADE CONSTRAINTS PURGE;
    
-- LIMPARA A LIXEIRA (Só no Oracle)
    PURGE RECYCLEBIN;

--************************************ COMANDO ALTER E RENAME ************************************--
-- RENOMEANDO A TABELA ALUNO PARA ALUNOS_SHIFT COM O COMANDO ALTER TABLE
    ALTER TABLE ALUNOS
    RENAME TO ALUNOS_SHIFT;
    
-- RENOMEANDO A TABELA ALUNO PARA ALUNOS_SHIFT COM O COMANDO RENAME
   RENAME ALUNOS_SHIFT TO ALUNOS;

--****************************************************************
-- RENAME É PARA QUALQUER TIPO DE OBJETO, POR EXEMPLO PARA VISÃO: 
--****************************************************************
    CREATE SEQUENCE SEQ_ALUNOS;
--CURIOSIDADE, NOTE A MENSAGEM RETORNADA APÓS O RENAME DA SEQUENCIA
    RENAME SEQ_ALUNOS TO SEQ_ALUNOS_SHIFT;
     
--************************************ TRUNCATE TABLE ************************************--
/* DEMONSTRANDO: 
   NÃO SE PREOCUPE COM OS COMANDOS
   COMMIT, INSERT E SELECT POIS SERÃO VISTOS
   NAS PRÓXIMAS AULAS. 
*/
    drop table produtos purge;
    
    create table produtos
    (cod_produto number(5),
    nome varchar(100),
    valor number(7,2));

-- BLOCO ANÔNIMO (ISSO É PROGRAMAÇÃO PL/SQL) 
-- INSERE 10000 LINHAS NA TABELA PRODUTOS PARA FINS DE DEMONSTRAÇÃO 
    begin
       for i in 1..10000 loop
           insert into produtos
           values (i,'Produto 1',10+1);
        end loop;
    end;
    /
-- CONFIRMANDO A QTD DE LINHAS ANTE DO TRUNCATE
    SELECT COUNT(*) FROM PRODUTOS;

--ESVAZIA A TABELA
    TRUNCATE TABLE PRODUTOS;

-- CONFIRMANDO A QTD DE LINHAS APÓS O TRUNCATE
    SELECT COUNT(*) FROM PRODUTOS;


--************************************ SEQUENCIA ************************************--
-- ANTES, UM EXEMPLO PARA CONTEXTUALIZAR
    DROP TABLE LIVROS PURGE;
    
    CREATE TABLE LIVROS
    (COD_LIVRO NUMBER PRIMARY KEY,
    NOME_LIVRO VARCHAR(50));

-- TESTE 1
    DROP SEQUENCE SEQ_LIVROS; -- SÓ PARA GARANTIR
    
    CREATE SEQUENCE SEQ_LIVROS;

    INSERT INTO LIVROS
    VALUES (SEQ_LIVROS.NEXTVAL,'Sistemas de BD');
    INSERT INTO LIVROS
    VALUES (SEQ_LIVROS.NEXTVAL,'SQL');
    INSERT INTO LIVROS
    VALUES (SEQ_LIVROS.NEXTVAL,'PROGRAMAÇÃO PL/SQL');
    INSERT INTO LIVROS
    VALUES (SEQ_LIVROS.NEXTVAL,'Mineração de Dados no Oracle');
    INSERT INTO LIVROS
    VALUES (SEQ_LIVROS.NEXTVAL,'Otimização de BD');
    commit;
    
    SELECT * FROM LIVROS;
    

-- TESTE 2
    TRUNCATE TABLE LIVROS;
    DROP SEQUENCE SEQ_LIVROS;
    
    CREATE SEQUENCE SEQ_LIVROS
    START WITH 10
    INCREMENT BY 5;

    INSERT INTO LIVROS
    VALUES (SEQ_LIVROS.NEXTVAL,'Sistemas de BD');
    INSERT INTO LIVROS
    VALUES (SEQ_LIVROS.NEXTVAL,'SQL');
    INSERT INTO LIVROS
    VALUES (SEQ_LIVROS.NEXTVAL,'PROGRAMAÇÃO PL/SQL');
    INSERT INTO LIVROS
    VALUES (SEQ_LIVROS.NEXTVAL,'Mineração de Dados no Oracle');
    INSERT INTO LIVROS
    VALUES (SEQ_LIVROS.NEXTVAL,'Otimização de BD');
    commit;
    
    SELECT * FROM LIVROS;
        
 
   
