-- EXERCICIOS AULA 06
-- 1. TRAZER TODOS FUNCIONARIOS LISTANDO CODIGO, NOME, DATA NASCIMENTO E NOME DEPTO. FILTRAR SOMENTE MORADORES VILA MARIANA
SELECT F.CD_FUNCIONARIO, F.NM_FUNCIONARIO, F.DT_NASCIMENTO, B.NM_BAIRRO
FROM  DB_FUNCIONARIO F JOIN DB_END_FUNC EF
ON F.CD_FUNCIONARIO = EF.CD_FUNCIONARIO
JOIN DB_LOGRADOURO L
ON L.CD_LOGRADOURO = EF.CD_LOGRADOURO
JOIN DB_BAIRRO B
ON B.CD_BAIRRO = L.CD_BAIRRO 
WHERE NM_BAIRRO = 'Vila Mariana';


-- 2. SELECIONAR TODOS FUNCIONARIOS LISTANDO CODIGO, NOME E ENDERECO COMPLETO. FILTRAR MORADORES DA SAUDE COM 4 ESTRELAS OU MAIS
SELECT F.CD_FUNCIONARIO, F.NM_FUNCIONARIO, EF.NR_END, L.NM_LOGRADOURO, B.NM_BAIRRO, C.NM_CIDADE, E.NM_ESTADO
FROM DB_FUNCIONARIO F JOIN DB_END_FUNC EF
ON F.CD_FUNCIONARIO = EF.CD_FUNCIONARIO
JOIN DB_LOGRADOURO L
ON L.CD_LOGRADOURO = EF.CD_LOGRADOURO
JOIN DB_BAIRRO B
ON B.CD_BAIRRO = L.CD_BAIRRO
JOIN DB_CIDADE C
ON C.CD_CIDADE = B.CD_CIDADE
JOIN DB_ESTADO E
ON E.SG_ESTADO = C.SG_ESTADO
--JOIN DB_CONTATO CT
--ON C.CD_CIDADE = CT.CD_CIDADE
--JOIN DB_CLIENTE CL
--ON CL.NR_CLIENTE = CT.NR_CLIENTE
WHERE B.NM_BAIRRO = 'Vila Mariana';
