SELECT LAST_NAME, DEPARTMENT_NAME, STREET_ADDRESS, REGION_NAME, JOB_TITLE
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN LOCATIONS L
ON L.LOCATION_ID = D.LOCATION_ID
JOIN COUNTRIES C
ON C.COUNTRY_ID = L.COUNTRY_ID
JOIN REGIONS R
ON R.REGION_ID = C.REGION_ID
JOIN JOBS J
ON J.JOB_ID = E.JOB_ID;


-- Query Hierarquica
SELECT LEVEL, LAST_NAME, JOB_ID
FROM EMPLOYEES
START WITH EMPLOYEE_ID = 101
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;